project:
  type: book
  output-dir: docs

execute: 
  kernel: dataviz

# language:
#   label:
#     fig: "Figure "
#     tab: "Table "
#   ui:
#     edit: "Edit"
#     chapter_name: "Chapter "

# format:
#   html:
#     # built-in Bootswatch theme (cosmo, flatly, darkly, etc.)
#     theme: cosmo
#     # add a stylesheet for overrides
#     # css: styles.css
#     # table of contents for each page / book-level TOC
#     toc: true
#     toc-location: left
#     toc-depth: 1
#     # syntax highlighting (can supply one style or two: light/dark)
#     highlight-style: github

#   pdf:
#     # documentclass, engine and small LaTeX injection
#     documentclass: krantz
#     pdf-engine: lualatex
#     include-in-header:
#       text: |
#         \usepackage{float}
#         \floatplacement{figure}{H}

bibliography:
  - book.bib
#   - packages.bib

format:
  html:
    css: style.css
    df-print: paged         # Quarto supports df-print for HTML
    theme: cosmo
    toc: true
    toc-location: left
    toc-depth: 5
    highlight-style: github
    number-sections: true
    number-depth: 3
    page-layout: article
    grid:
      sidebar-width: 300px
      body-width: 1200px
      margin-width: 0px
      gutter-width: 200px

  # pdf:
  #   documentclass: krantz
  #   biblio-style: apalike   # LaTeX bibliography style for PDF builds (natbib/biblatex)
  #   geometry: "left=1.5in, right=1.5in, top=1.25in, bottom=1.25in"
  #   colorlinks: true
  #   urlcolor: blue
  #   include-in-header:
  #     text: |
  #       \usepackage{float}
  #       \floatplacement{figure}{H}


book:
  title: "Data Analysis and Visualization in Python"
  chapters:
    - index.qmd
    - topic00_Introduction/script/script_00.qmd
    - part: "I Get"
      chapters: 
        - topic01_Python_Basics/script/script_01.qmd
        - topic02_Data_Wrangling/script/script_02.qmd
        - topic03_Tidy_Data/script/script_03.qmd
        - topic04_Plotting-I/script/script_04.qmd
     
  appendices: 
    - appendix04_Probabilities/script/appendix_04.qmd

